---
- block:
  - name: Copy configuration file
    template: src=config.yml dest=/home/ansibleuser/config.yml
  - name: Copy jar file
    copy: src=../target/com-ex1-sample.jar dest=/home/ansibleuser/com-ex1-sample.jar
  - name: Copy all dependencies
    copy: src=../target/dependency/ dest=/home/ansibleuser/
  - name: Run jar file
    shell: sh java -jar /home/ansibleuser/com-ex1-sample.jar &
  - name: Waiting for server
    wait_for: 
      port: 8761